#
# Copyright 2022 Advantech
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_TARGET_IMX8MM_EBCRS16A1_2G
obj-y += imx8mm_ebcrs16a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing_ebcrs16a1_2G.o
endif
endif
