#
# Copyright 2018 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_TARGET_IMX8MM_RSB3730A1_2G
obj-y += imx8mm_rsb3730a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing_rsb3730a1_2G.o
endif
endif

ifdef CONFIG_TARGET_IMX8MM_RSB3730A1_1G
obj-y += imx8mm_rsb3730a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing_rsb3730a1_1G.o
endif
endif
