#
# Copyright 2023 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_TARGET_IMX95_AOM5521A1_16G
obj-y += imx95_aom5521a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
endif
endif

ifdef CONFIG_TARGET_IMX95_AOM5521A1_8G
obj-y += imx95_aom5521a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
endif
endif
