# SPDX-License-Identifier: GPL-2.0+

ifdef CONFIG_TARGET_IMX8ULP_ROM2620A1
obj-y	+= imx8ulp_rom2620a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_TARGET_IMX8ULP_ROM2620A1) += lpddr4_timing_rom2620a1_2G.o
endif
endif
