#
# Copyright 2022 Advantech
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_TARGET_IMX8MM_RSB3730A2_2G
obj-y += imx8mm_rsb3730a2.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing_rsb3730a2_2G.o
endif
endif

ifdef CONFIG_TARGET_IMX8MM_RSB3730A2_4G
obj-y += imx8mm_rsb3730a2.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing_rsb3730a2_4G.o
endif
endif
