#
# Copyright 2024 Advantech
#
# SPDX-License-Identifier:      GPL-2.0+
#
ifdef CONFIG_TARGET_IMX93_AFEE320A1
obj-y += imx93_afee320a1.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_TARGET_IMX93_AFEE320A1) += lpddr4x_timing_afee320a1.o lpddr4x_timing_1866mts.o
endif
endif
